import { FileToGenerate } from '../file-generator.js';

export function generateMobileFiles(
  projectName: string,
  framework: 'flutter' | 'react-native',
  variables: Record<string, string>
): FileToGenerate[] {
  if (framework === 'flutter') {
    const org = variables.ORG_DOMAIN || 'com.helix';

    return [
      {
        relativePath: 'pubspec.yaml',
        content: `name: ${projectName.toLowerCase()}
description: "A new Flutter project created with HELIX."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
`,
      },
      {
        relativePath: 'lib/main.dart',
        content: `import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final counterProvider = StateProvider<int>((ref) => 0);

void main() {
  runApp(const ProviderScope(child: HelixApp()));
}

class HelixApp extends StatelessWidget {
  const HelixApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${projectName}',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const CounterScreen(),
    );
  }
}

class CounterScreen extends ConsumerWidget {
  const CounterScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final count = ref.watch(counterProvider);

    return Scaffold(
      appBar: AppBar(title: const Text('${projectName}')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('Button click counter:'),
            Text('\$count', style: Theme.of(context).textTheme.headlineMedium),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => ref.read(counterProvider.notifier).state++,
        child: const Icon(Icons.add),
      ),
    );
  }
}
`,
      },
    ];
  }

  // React Native / Expo Router
  return [
    {
      relativePath: 'package.json',
      content: JSON.stringify(
        {
          name: projectName,
          version: '1.0.0',
          scripts: {
            start: 'expo start',
            android: 'expo start --android',
            ios: 'expo start --ios',
            web: 'expo start --web',
          },
          dependencies: {
            expo: '~51.0.0',
            'expo-router': '~3.5.0',
            'react-native': '0.74.1',
            react: '18.2.0',
          },
          devDependencies: {
            '@types/react': '~18.2.79',
            typescript: '~5.3.3',
          },
        },
        null,
        2
      ) + '\n',
    },
    {
      relativePath: 'app.json',
      content: JSON.stringify(
        {
          expo: {
            name: projectName,
            slug: projectName.toLowerCase(),
            version: '1.0.0',
            orientation: 'portrait',
            scheme: variables.SCHEME || 'helixapp',
            userInterfaceStyle: 'automatic',
          },
        },
        null,
        2
      ) + '\n',
    },
    {
      relativePath: 'app/_layout.tsx',
      content: `import { Stack } from 'expo-router';

export default function RootLayout() {
  return (
    <Stack>
      <Stack.Screen name="index" options={{ title: '${projectName}' }} />
    </Stack>
  );
}
`,
    },
    {
      relativePath: 'app/index.tsx',
      content: `import { StyleSheet, Text, View } from 'react-native';

export default function HomeScreen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Welcome to ${projectName}!</Text>
      <Text style={styles.subtitle}>Expo Router mobile app generated by HELIX</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  title: { fontSize: 22, fontWeight: 'bold', marginBottom: 8 },
  subtitle: { fontSize: 14, color: '#666' },
});
`,
    },
  ];
}
