import { FileToGenerate } from '../file-generator.js';

export function generateGameEngineFiles(
  projectName: string,
  engine: 'unity' | 'godot' | 'rpgm' | 'renpy',
  variables: Record<string, string>
): FileToGenerate[] {
  if (engine === 'godot') {
    const width = variables.WINDOW_WIDTH || '1280';
    const height = variables.WINDOW_HEIGHT || '720';

    return [
      {
        relativePath: 'project.godot',
        content: `config_version=5

[application]
config/name="${projectName}"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.3", "Forward Plus")

[display]
window/size/viewport_width=${width}
window/size/viewport_height=${height}

[rendering]
renderer/rendering_method="forward_plus"
`,
      },
      {
        relativePath: 'scripts/player.gd',
        content: `class_name Player
extends CharacterBody2D

@export var speed: float = 300.0
@export var jump_velocity: float = -400.0

var gravity: int = ProjectSettings.get_setting("physics/2d/default_gravity")

func _physics_process(delta: float) -> void:
	if not is_on_floor():
		velocity.y += gravity * delta

	if Input.is_action_just_pressed("ui_accept") and is_on_floor():
		velocity.y = jump_velocity

	var direction: float = Input.get_axis("ui_left", "ui_right")
	if direction:
		velocity.x = direction * speed
	else:
		velocity.x = move_toward(velocity.x, 0, speed)

	move_and_slide()
`,
      },
      {
        relativePath: 'scenes/main.tscn',
        content: `[gd_scene format=3 uid="uid://helixgame001"]

[node name="Main" type="Node2D"]

[node name="Label" type="Label" parent="."]
offset_left = 40.0
offset_top = 40.0
offset_right = 400.0
offset_bottom = 80.0
text = "Welcome to ${projectName} (Godot 4 - HELIX CLI)"
`,
      },
    ];
  }

  if (engine === 'rpgm') {
    const pluginName = variables.PLUGIN_NAME || 'Helix_CustomSystem';
    const author = variables.AUTHOR_NAME || 'HELIX Developer';
    const target = variables.TARGET_ENGINE || 'MZ';

    return [
      {
        relativePath: `js/plugins/${pluginName}.js`,
        content: `/*:
 * @target ${target}
 * @plugindesc v1.0.0 Custom gameplay mechanics generated by HELIX CLI
 * @author ${author}
 * 
 * @help ${pluginName}.js
 * 
 * This plugin introduces core gameplay hooks and commands.
 * 
 * @param BonusExpMultiplier
 * @text Bonus EXP Multiplier
 * @desc Experience multiplier applied to party members.
 * @type number
 * @decimals 2
 * @default 1.50
 * 
 * @command GrantBonusGold
 * @text Grant Bonus Gold
 * @desc Grants bonus gold to party.
 * 
 * @arg amount
 * @text Amount
 * @type number
 * @default 100
 */

(() => {
    'use strict';
    const pluginName = '${pluginName}';
    const parameters = PluginManager.parameters(pluginName);
    const expMultiplier = Number(parameters['BonusExpMultiplier'] || 1.0);

    if (PluginManager.registerCommand) {
        PluginManager.registerCommand(pluginName, 'GrantBonusGold', args => {
            $gameParty.gainGold(Number(args.amount));
        });
    }

    const _Game_Actor_changeExp = Game_Actor.prototype.changeExp;
    Game_Actor.prototype.changeExp = function(exp, show) {
        _Game_Actor_changeExp.call(this, Math.round(exp * expMultiplier), show);
    };

    console.log(\`[\${pluginName}] Initialized successfully via HELIX CLI\`);
})();
`,
      },
    ];
  }

  if (engine === 'renpy') {
    const novelTitle = variables.NOVEL_TITLE || projectName;
    const author = variables.AUTHOR_NAME || 'HELIX Studio';

    return [
      {
        relativePath: 'game/script.rpy',
        content: `define e = Character("Eileen", color="#c8ffc8")

label start:
    scene bg room
    show eileen happy at center
    
    e "Welcome to ${novelTitle}!"
    e "Created with HELIX CLI and powered by the Ren'Py visual novel engine."

    menu:
        "Begin Adventure":
            jump chapter_one
        "Quit":
            return

label chapter_one:
    e "Our journey begins now."
    return
`,
      },
      {
        relativePath: 'game/options.rpy',
        content: `define config.name = _("${novelTitle}")
define gui.show_name = True
define config.version = "1.0"
define build.name = "${projectName.toLowerCase()}"
define config.has_sound = True
define config.has_music = True
define config.has_voice = True
`,
      },
    ];
  }

  // Default: Unity
  return [
    {
      relativePath: 'Assets/Scripts/Helix.Gameplay.asmdef',
      content: JSON.stringify(
        {
          name: 'Helix.Gameplay',
          rootNamespace: 'Helix.Gameplay',
          references: [],
          includePlatforms: [],
          excludePlatforms: [],
          allowUnsafeCode: false,
          overrideReferences: false,
          precompiledReferences: [],
          autoReferenced: true,
          defineConstraints: [],
          versionDefines: [],
          noEngineReferences: false,
        },
        null,
        2
      ) + '\n',
    },
    {
      relativePath: 'Assets/Scripts/PlayerController.cs',
      content: `using UnityEngine;

namespace Helix.Gameplay
{
    [RequireComponent(typeof(CharacterController))]
    public class PlayerController : MonoBehaviour
    {
        [Header("Movement")]
        [SerializeField] private float speed = 6f;
        [SerializeField] private float gravity = -9.81f;

        private CharacterController controller;
        private Vector3 velocity;

        private void Awake()
        {
            controller = GetComponent<CharacterController>();
        }

        private void Update()
        {
            float x = Input.GetAxis("Horizontal");
            float z = Input.GetAxis("Vertical");

            Vector3 move = transform.right * x + transform.forward * z;
            controller.Move(move * speed * Time.deltaTime);

            if (controller.isGrounded && velocity.y < 0)
            {
                velocity.y = -2f;
            }

            velocity.y += gravity * Time.deltaTime;
            controller.Move(velocity * Time.deltaTime);
        }
    }
}
`,
    },
  ];
}
